title: Sakanasaigao's Homepage
page-top-title: Sakanasaigao
top-section-bg-text: Never give up!
home-subtitle: Sakanasaigao&ensp;|&ensp;傅明浩
copyright-text: '&copy; Sakanasaigao 2023-2025. All Rights Reserved.'
